### ISSUE TITLE
OOS Todo

### ISSUE THREAD

**Issue by pwmckenna** [pwmckenna/til#20]
- [ ] [React Transform is going away](https://github.com/gaearon/babel-plugin-react-transform/issues/90).  
  Update the readme of [react-transform-hoc](https://github.com/pwmckenna/react-transform-hoc), and rewrite existing transforms as higher order components and just use react-transform-hoc. This will make the hocs reusable in whatever new hot reloading world exists in the future.
- [x] [Document the internal helpers of recompose](https://github.com/acdlite/recompose/issues/66) so I can use them.
- [ ] Document how well maintained projects are (most are abandoned). Add contributor lists. Perhaps use the [no-maintenance-intended](https://github.com/gaearon/react-pure-render#no-maintenance-intended) badge.
- [ ] Figure out how to indicate that React Resolver resolvers have missed the boat on the server side. 
- [ ] get external feedback on Fluxible / React Resolver library.
